### PR TITLE
fix: async upgrade

### PR DESCRIPTION
**Pull request by rramk**

### CODE REVIEW

**Comment by rramk** [comment]
@alexguan Please take a look. This will fix the upgrade issue in 1.1.2 as mentioned in this [issue](https://github.com/alexguan/node-zookeeper-client/issues/121)

**Comment by rramk** [comment]
Hi @alexguan, could you please look into this. It's a bit urgent

**Comment by alexguan** [comment]
I'm quite busy this week, most likely this will be pushed to next week. If this is a fundamental issue as described in #121, we should get more bug reports, right?

**Comment by rramk** [comment]
No idea why anyone else didn't raise the issue but I can see it too. Basically, nothing works because `async` had a breaking change which I didn't heed (my bad)
@alexguan

**Comment by wuteng606** [comment]
I also encountered the same problem. I hope can merge the code as soon as possible.

**Comment by JamesYYang** [comment]
same problem +1

**Comment by luckyyyyy** [comment]
same problem +2

**Comment by luckyyyyy** [comment]
@alexguan I hope can merge the code as soon as possible and publish, this issue is urgent

**Comment by jmaicher** [comment]
Can confirm, we're also affected by this.

**Pull request merged**
