### PR TITLE
Upgrade dependencies to resolve vulnerabilities

### PR DESCRIPTION
**Pull request by rramk**

### CODE REVIEW

**Comment by rramk** [comment]
@alexguan Kindly approve/merge this PR. 
Thank you

**Comment by alexguan** [comment]
Can you update the CHANGELOG.md as well?

**Comment by rramk** [comment]
Updated the CHANGELOG. Thanks @alexguan

**Comment by rramk** [comment]
@alexguan Could you please release npm package for the latest 1.1.2 version ?

**Comment by alexguan** [comment]
It's published

**Pull request merged**
