### PR TITLE
Replaced JSLint with ESLint.

### PR DESCRIPTION
**Pull request by lightswitch05**
I'm looking to make some contributions to this project, but I was unable to get JSLint 0.1.9 run on my computer. Looks like it is a common problem with macs and this old version (latest is 0.10.1). JSLint 0.2.0 and greater runs fine, but they changed the linting rules and do not have configuration options to get the project passing without major changes. 

ESLint has many well documented configuration options. For this pull request I configured it to be at the strictest level without requiring too many changes. Most are just whitespace. Many options are stylelistic, and are therefore quite subjective. I tried my best to determine your prefered styles based on the existing code. Please let me know if you disagree with any of the rules and I will happily remove them.

### CODE REVIEW

**Comment by alexguan** [comment]
Thanks for the PR, I will take a look. When I originally wrote the code, I used JSLint to force certain style I prefer. Since then ESLint has been evolving quickly, it's probably a good time to make this change.

**Comment by magicdawn** [comment]
+1 on ESLint

**Comment by lightswitch05** [comment]
Thanks for merging this! Any comments on #42 or #43?

**Comment by alexguan** [comment]
I will get to them soon.

**Pull request merged**
